title: TJ Mazeika
description: >-
  Home of TJ Mazeika.
baseurl: ""
url: "https://mazeika.me"

defaults:
- scope:
    path: ""
    type: "posts"
  values:
    layout: "post"

kramdown:
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
