name: static-site-build
on: [push]
jobs:
  static-site-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install
        run: yarn --frozen-lockfile

      - name: build
        run: yarn build

      - name: github-pages
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages
          folder: build/public
